// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int SoldCount { get; set; }

    public string Description { get; set; }

    public int ProductInStock { get; set; }

    public int? CategoryId { get; set; }

    public int? StatusId { get; set; }

    public DateOnly? StockInDate { get; set; }

    public decimal? MarketPrice { get; set; }

    public decimal? SellPrice { get; set; }

    public decimal? StockPrice { get; set; }

    public string Img { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ProductStatus Status { get; set; }
}