//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Pages.Customer
{
    partial class LoginForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginForm));
            panelLogin = new Panel();
            buttonRegister = new Button();
            labelSubtitle = new Label();
            buttonLogin = new Button();
            textBoxPassword = new TextBox();
            labelPassword = new Label();
            textBoxUsername = new TextBox();
            labelUsername = new Label();
            pictureBoxLogo = new PictureBox();
            labelTitle = new Label();
            panelLogin.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBoxLogo).BeginInit();
            SuspendLayout();
            // 
            // panelLogin
            // 
            panelLogin.BackColor = Color.FromArgb(237, 224, 207);
            panelLogin.Controls.Add(buttonRegister);
            panelLogin.Controls.Add(labelSubtitle);
            panelLogin.Controls.Add(buttonLogin);
            panelLogin.Controls.Add(textBoxPassword);
            panelLogin.Controls.Add(labelPassword);
            panelLogin.Controls.Add(textBoxUsername);
            panelLogin.Controls.Add(labelUsername);
            panelLogin.Controls.Add(pictureBoxLogo);
            panelLogin.Controls.Add(labelTitle);
            panelLogin.Location = new Point(200, 50);
            panelLogin.Name = "panelLogin";
            panelLogin.Size = new Size(400, 550);
            panelLogin.TabIndex = 0;
            // 
            // buttonRegister
            // 
            buttonRegister.BackColor = Color.FromArgb(138, 80, 20);
            buttonRegister.FlatAppearance.BorderSize = 0;
            buttonRegister.FlatStyle = FlatStyle.Flat;
            buttonRegister.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point, 0);
            buttonRegister.ForeColor = Color.White;
            buttonRegister.Location = new Point(50, 480);
            buttonRegister.Name = "buttonRegister";
            buttonRegister.Size = new Size(300, 35);
            buttonRegister.TabIndex = 8;
            buttonRegister.Text = "Chưa có tài khoản? Đăng ký ngay";
            buttonRegister.UseVisualStyleBackColor = false;
            buttonRegister.Click += buttonRegister_Click;
            // 
            // labelSubtitle
            // 
            labelSubtitle.AutoSize = true;
            labelSubtitle.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point, 0);
            labelSubtitle.ForeColor = Color.FromArgb(77, 58, 41);
            labelSubtitle.Location = new Point(100, 450);
            labelSubtitle.Name = "labelSubtitle";
            labelSubtitle.Size = new Size(207, 23);
            labelSubtitle.TabIndex = 7;
            labelSubtitle.Text = "HeartSteel Cosmetic Store";
            // 
            // buttonLogin
            // 
            buttonLogin.BackColor = Color.FromArgb(77, 58, 41);
            buttonLogin.FlatAppearance.BorderSize = 0;
            buttonLogin.FlatStyle = FlatStyle.Flat;
            buttonLogin.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            buttonLogin.ForeColor = Color.White;
            buttonLogin.Location = new Point(50, 390);
            buttonLogin.Name = "buttonLogin";
            buttonLogin.Size = new Size(300, 45);
            buttonLogin.TabIndex = 6;
            buttonLogin.Text = "Đăng nhập";
            buttonLogin.UseVisualStyleBackColor = false;
            buttonLogin.Click += buttonLogin_Click;
            // 
            // textBoxPassword
            // 
            textBoxPassword.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            textBoxPassword.Location = new Point(50, 330);
            textBoxPassword.Name = "textBoxPassword";
            textBoxPassword.PasswordChar = '●';
            textBoxPassword.Size = new Size(300, 34);
            textBoxPassword.TabIndex = 5;
            textBoxPassword.KeyPress += textBoxPassword_KeyPress;
            // 
            // labelPassword
            // 
            labelPassword.AutoSize = true;
            labelPassword.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            labelPassword.ForeColor = Color.FromArgb(77, 58, 41);
            labelPassword.Location = new Point(50, 300);
            labelPassword.Name = "labelPassword";
            labelPassword.Size = new Size(98, 28);
            labelPassword.TabIndex = 4;
            labelPassword.Text = "Mật khẩu:";
            // 
            // textBoxUsername
            // 
            textBoxUsername.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            textBoxUsername.Location = new Point(50, 250);
            textBoxUsername.Name = "textBoxUsername";
            textBoxUsername.Size = new Size(300, 34);
            textBoxUsername.TabIndex = 3;
            textBoxUsername.KeyPress += textBoxUsername_KeyPress;
            // 
            // labelUsername
            // 
            labelUsername.AutoSize = true;
            labelUsername.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            labelUsername.ForeColor = Color.FromArgb(77, 58, 41);
            labelUsername.Location = new Point(50, 220);
            labelUsername.Name = "labelUsername";
            labelUsername.Size = new Size(98, 28);
            labelUsername.TabIndex = 2;
            labelUsername.Text = "Tài khoản:";
            // 
            // pictureBoxLogo
            // 
            pictureBoxLogo.Image = (Image)resources.GetObject("pictureBoxLogo.Image");
            pictureBoxLogo.Location = new Point(150, 80);
            pictureBoxLogo.Name = "pictureBoxLogo";
            pictureBoxLogo.Size = new Size(100, 100);
            pictureBoxLogo.SizeMode = PictureBoxSizeMode.Zoom;
            pictureBoxLogo.TabIndex = 1;
            pictureBoxLogo.TabStop = false;
            // 
            // labelTitle
            // 
            labelTitle.AutoSize = true;
            labelTitle.Font = new Font("Segoe UI", 18F, FontStyle.Bold, GraphicsUnit.Point, 0);
            labelTitle.ForeColor = Color.FromArgb(77, 58, 41);
            labelTitle.Location = new Point(150, 20);
            labelTitle.Name = "labelTitle";
            labelTitle.Size = new Size(110, 41);
            labelTitle.TabIndex = 0;
            labelTitle.Text = "LOGIN";
            // 
            // LoginForm
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(255, 255, 255);
            ClientSize = new Size(800, 650);
            Controls.Add(panelLogin);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "LoginForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Đăng nhập - HeartSteel Cosmetic";
            panelLogin.ResumeLayout(false);
            panelLogin.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBoxLogo).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private Panel panelLogin;
        private Label labelTitle;
        private PictureBox pictureBoxLogo;
        private Label labelUsername;
        private TextBox textBoxUsername;
        private Label labelPassword;
        private TextBox textBoxPassword;
        private Button buttonLogin;
        private Label labelSubtitle;
        private Button buttonRegister;
    }
}
